from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from models.db import init_db
from models.analytics import PageView, DonationEvent
from models.agent import AgentState, AgentDecision, PerformanceSnapshot
from models.feedback import Feedback
from routers import portfolio, recommendations, watchlist, congress, analytics, donations, feedback, marketing, autopilot
from services.scheduler import start_scheduler, stop_scheduler
import logging, os

logging.basicConfig(level=logging.INFO)

@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_db()
    start_scheduler()
    yield
    stop_scheduler()

app = FastAPI(
    title="TradeWise API",
    description="AI-assisted trading — free forever, donate if you profit.",
    version="0.3.0",
    lifespan=lifespan,
)

ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", "http://localhost:5173,http://localhost:3000").split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

for r in [portfolio, recommendations, watchlist, congress, analytics, donations, feedback, marketing, autopilot]:
    app.include_router(r.router)

@app.get("/health")
async def health():
    return {"status": "ok", "version": "0.3.0", "live_trading": bool(os.getenv("ALPACA_LIVE_API_KEY"))}

@app.get("/legal/disclaimer")
async def disclaimer():
    return {
        "disclaimer": (
            "TradeWise is an educational paper and live trading tool. "
            "NOTHING on this platform is financial advice. "
            "AI signals are generated by a language model and may be wrong. "
            "You can lose real money in live mode. "
            "TradeWise is not a registered investment advisor or broker-dealer. "
            "Past performance does not guarantee future results. "
            "Always consult a licensed financial advisor before trading with real money."
        ),
        "live_trading_warning": (
            "Live trading executes real orders with real money via Alpaca Markets. "
            "TradeWise bears no responsibility for trading losses. "
            "Use live mode at your own risk."
        ),
        "congressional_data": (
            "Congressional trade data is public under the STOCK Act of 2012. "
            "It is not insider information and is available to all citizens."
        ),
    }

@app.get("/config/public")
async def public_config():
    """Frontend config — which features are enabled."""
    return {
        "live_trading_available": bool(os.getenv("ALPACA_LIVE_API_KEY")),
        "stripe_available": bool(os.getenv("STRIPE_SECRET_KEY")),
        "app_url": os.getenv("APP_URL", ""),
    }
